version: '2'
services:
  webserver:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - gitserver
  gitserver:
    image: gogs/gogs
    expose:
    - "3000"
    ports:
      - "10022:22"
    volumes:
      - /var/gogs:/data
