version: '2'

services:
  web:
    image: nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - NGINX_HOST=127.30.27.65
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - git

  git:
    image: gogs/gogs
    volumes:
      - /var/gogs:/data
