version: '2'

services:
  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=127.30.27.65
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - git:ro
    depends_on:
      - git
    links:
      - git:git

  git:
    image: gogs/gogs
    expose:
      - "3000"
    ports:
      - "10022:22"
    volumes:
      - /var/gogs:/data
