version: '2'

services:
  webserver:
    image: nginx
    # build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - gitserver
    # links:
      # - gitserver
    hostname: webserver
    networks:
      - my-network

  gitserver:
    image: gogs/gogs
    expose:
    - "3000"
    ports:
      - "10022:22"
    volumes:
      - /var/gogs:/data
    hostname: gitserver
    networks:
      - my-network

networks:
  my-network:
    external: true
